[package]
name = "rclrs"
version = "0.1.0"
authors = ["Esteve Fernandez <esteve@apache.org>"]
edition = "2018"

[dependencies]
rclrs_common = { path = "../rclrs_common" }
rcl_sys = { path = "../rcl_sys" }
